# .github/workflows/deploy.yml
name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # 替换为你需要的 Python 版本

      - name: Create project directory
        run: |
          mkdir -p flask-app
          cd flask-app
          echo "Project directory created."

      - name: Install dependencies
        run: |
          cd flask-app
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd flask-app
          echo "No tests found"
