name: Python application

on:
  push:
    branches:
      - main  # 触发工作流的分支名称，您可以根据需要修改

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 检出代码

    - name: Set up Python
      uses: actions/setup-python@v4  # 设置 Python 环境
      with:
        python-version: '3.9'  # 指定 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 安装 Python 依赖

    - name: Run tests
      run: |
        # 在这里运行测试，假设使用 pytest
        pytest  # 如果您有测试脚本，您可以在这里运行
        echo "No tests to run"  # 如果没有测试脚本，可以省略这一行

    - name: Deploy to Heroku
      uses: akshatmittal/heroku-deploy@v1  # 使用 Heroku 部署 Action
      with:
        api-key: ${{ secrets.HEROKU_API_KEY }}  # 从 GitHub Secrets 获取 Heroku API Key
        app-name: ${{ secrets.HEROKU_APP_NAME }}  # 从 GitHub Secrets 获取 Heroku 应用名称
        branch: main  # 部署的分支名称
