name: Deploy Flask App

on:
  push:
    branches:
      - main  # 监听 main 分支上的推送事件

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用最新版本的 Ubuntu 运行环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 检出你的代码到 GitHub Actions 运行环境

    - name: Set up Python
      uses: actions/setup-python@v4  # 设置 Python 环境
      with:
        python-version: '3.8'  # 使用 Python 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 安装项目依赖

    - name: Run tests
      run: |
        # 在这里可以添加测试步骤
        echo "Tests passed"

    - name: Deploy to server
      run: |
        # 部署到你的服务器的命令
        # 这一步根据你的具体部署方案进行调整
        echo "Deploying to server"
